name: Deploy Resume Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install HTML/CSS/JS validators
      run: |
        npm install -g html-validate
        npm install -g csslint
        npm install -g jshint
        
    - name: Validate HTML
      run: |
        echo "Validating HTML files..."
        html-validate index.html portfolio-details.html service-details.html starter-page.html
        
    - name: Validate CSS
      run: |
        echo "Validating CSS files..."
        csslint assets/css/main.css || true  # Continue on CSS warnings
        
    - name: Validate JavaScript
      run: |
        echo "Validating JavaScript files..."
        jshint assets/js/main.js || true  # Continue on JS warnings
        
    - name: Check for broken links
      run: |
        echo "Checking for broken links..."
        # Install link checker
        pip install linkchecker
        linkchecker --check-extern index.html || true
        
    - name: Performance audit
      run: |
        echo "Running performance audit..."
        # Install Lighthouse CI
        npm install -g @lhci/cli@0.12.x
        # Run basic performance check
        lhci autorun --collect.url="file://$(pwd)/index.html" --collect.numberOfRuns=1 || true
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        cname: # Add your custom domain here if you have one
